### ISSUE TITLE
Pictures database

### ISSUE THREAD

**Issue by Alessandruino** [teradeep/demo-apps#2]
Hi Guys, i'm from the InMoov and Myrobotlab project... is the database with all the pictures you used to train this amazing app opensource too? i would love to train some opencv haar classifiers but i need a pictures database with positives and negatives...

Congratulations again for this amazing app...

Alessandro
InMoov and Myrobotlab italian ambassador

**Comment by culurciello** [comment]
Sorry Alessandro, the dataset is not for the public yet.
