### ISSUE TITLE
qlua: run.lua:103: attempt to call method 'init' (a nil value)

### ISSUE THREAD

**Issue by yashwant** [teradeep/demo-apps#6]
I am excited to try this out. I cloned the repo and followed mentioned steps to run it on mac.  But when I try to run it on my MacBook Pro (Retina, 13-inch, Mid 2014), I am getting error as: 

qlua: run.lua:103: attempt to call method 'init' (a nil value)
stack traceback:
	[C]: in function 'init'
	run.lua:103: in main chunk

I am running it in CPU only mode. 

What can be the reason of this error? How can I make it work?

**Comment by mvitez** [comment]
Have you modified the code? display:init is present in display.lua, which is required in line 14, so it seems weird to me that it's nil.

**Comment by yashwant** [comment]
Hi Marko,
No I haven't modified the code. And also display:init is present in display.lua file. I ran the command "qlua run.lua -z 2". I have also attached error screenshot in this comment. 

<img width="630" alt="teradeep_commands_snapshot" src="https://cloud.githubusercontent.com/assets/1837865/14203353/2af939f2-f81b-11e5-9b05-d721006e4f48.png">

**Comment by yashwant** [comment]
This issue is resolved now. On my machine require('display') was taking some other display.lua file. renamed the filename and it worked. @mvitez Thanks for the help.
