### ISSUE TITLE
cudnn issue on TX1

### ISSUE THREAD

**Issue by ChrisYang** [teradeep/demo-apps#7]
I was trying to run the opencv demo with 5000-categories model on TX1 and got the following error:

Error 4 in line cudnn/cudnn_basic.c:111
I checked the cudnn_basic.c line 111, there is an errorcheck:
		errcheck(cudaMalloc((void **)&t->storage->data, THFloatTensor_nElement(t) * datasize));

So it might be related to memory issue but I have no idea how to solve it. 
It works well if i switch to non-cudnn mode at an average speed of ~2FPS.

**Comment by mvitez** [comment]
Thank you very much for your report. Indeed thnets has been never tested with these networks on the TX1. I have fixed it, just pull the latest thnets.

**Comment by ChrisYang** [comment]
Thanks @mvitez. Now it works on TX1 at ~10FPS.
